nginx:
    image: danpersa/remindmetolive-nginx:latest
    links:
        - node1:node1
        - node2:node2
    ports:
        - "8080:8080"
node1:
    image: danpersa/remindmetolive-app:latest
    ports:
        - "3000"
node2:
    image: danpersa/remindmetolive-app:latest
    ports:
        - "3000"
