FROM node:8.6.0-alpine

RUN npm install pm2 -g

RUN mkdir -p /home/app/webapp/public
RUN mkdir -p /home/app/webapp/meta

COPY ./meta /home/app/webapp/meta
COPY ./dist/client /home/app/webapp/public
COPY ./dist/server /home/app/webapp/
COPY ./process-docker.yml /home/app/webapp/process.yml

WORKDIR /home/app/webapp

EXPOSE 3000
CMD ["pm2-docker", "/home/app/webapp/process.yml"]
